spring:
  profiles:
    active: default
  batch:
    initialize-schema: always
    job:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testcsvdb
    username: postgres
    password: postgres
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true