spring:
  profiles:
    active: default
  batch:
    initialize-schema: always
    job:
      enabled: true
  h2:
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true